"""
Relational schema for the feature store.

`build_schema_sql()` generates the CREATE TABLE statements for
user_features / item_features / interaction_features / feature_metadata.
The genre columns are generated from the live MovieLens genre vocabulary
(via `common.build_genre_matrix`) so the DDL never drifts from the
columns actually produced by the feature builders.
"""

import logging
from pathlib import Path
from typing import List

import pandas as pd

from src.config.config import MOVIES_FILE
from src.features.common import build_genre_matrix

logger = logging.getLogger(__name__)

_HEADER = """-- ============================================================
-- RecoMart Feature Store SQL Schema
-- Module: Feature Engineering & Feature Store (Member 3)
--
-- Auto-generated by src/features/sql_schema.py — regenerate instead of
-- hand-editing so it always matches the engineered feature columns.
-- ============================================================

"""


def _genre_column_ddl(prefix: str, slugs: List[str], sql_type: str) -> str:
    return ",\n".join(f"    {prefix}_{slug} {sql_type} DEFAULT 0" for slug in slugs)


def build_schema_sql() -> str:
    """Return the full schema.sql text as a string."""
    movies = pd.read_csv(MOVIES_FILE)
    _, genre_slugs, _ = build_genre_matrix(movies)

    pref_columns = _genre_column_ddl("pref", genre_slugs, "DECIMAL(4,3)")
    genre_columns = _genre_column_ddl("genre", genre_slugs, "SMALLINT")

    schema = f"""{_HEADER}
-- ------------------------------------------------------------
-- USER FEATURES
-- One row per user: activity, rating behaviour, temporal
-- patterns and a genre preference vector (pref_<genre>).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_features (
    user_id                     BIGINT PRIMARY KEY,
    num_ratings                 INTEGER NOT NULL,
    avg_rating                  DECIMAL(4,3),
    median_rating                DECIMAL(4,3),
    rating_std                  DECIMAL(5,4),
    min_rating                  DECIMAL(4,3),
    max_rating                  DECIMAL(4,3),
    most_active_hour             SMALLINT,
    most_active_dow               SMALLINT,
    activity_span_days           DECIMAL(10,3),
    avg_days_between_ratings      DECIMAL(10,3),
    num_distinct_genres_rated     SMALLINT,
    top_genre                   VARCHAR(64),
    top_genre_share              DECIMAL(5,4),
    genre_entropy                DECIMAL(6,4),
    num_tags_given               INTEGER,
    activity_percentile          DECIMAL(5,4),
{pref_columns},
    feature_version              VARCHAR(16) NOT NULL,
    computed_at                  TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_user_features_version ON user_features (feature_version);

-- ------------------------------------------------------------
-- ITEM FEATURES
-- One row per movie: popularity, rating behaviour, release
-- metadata, external ids and a genre content vector (genre_<genre>).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS item_features (
    movie_id                    BIGINT PRIMARY KEY,
    title                       VARCHAR(512),
    release_year                 SMALLINT,
    item_age_years                SMALLINT,
    is_new_release                BOOLEAN,
    num_genres                   SMALLINT,
    primary_genre                 VARCHAR(64),
    num_ratings                  INTEGER NOT NULL,
    avg_rating                  DECIMAL(4,3),
    median_rating                DECIMAL(4,3),
    rating_std                  DECIMAL(5,4),
    popularity_percentile         DECIMAL(5,4),
    recent_avg_rating             DECIMAL(4,3),
    rating_trend                 DECIMAL(5,4),
    num_tags                    INTEGER,
    top_tag                     VARCHAR(256),
    imdb_id                     VARCHAR(32),
    tmdb_id                     VARCHAR(32),
{genre_columns},
    feature_version              VARCHAR(16) NOT NULL,
    computed_at                  TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_item_features_version ON item_features (feature_version);
CREATE INDEX IF NOT EXISTS idx_item_features_popularity ON item_features (popularity_percentile);

-- ------------------------------------------------------------
-- INTERACTION FEATURES
-- One row per (user, movie, rating-event): recency/frequency,
-- rating deviations and similarity/cross features.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS interaction_features (
    interaction_id                    BIGINT PRIMARY KEY,
    user_id                          BIGINT NOT NULL REFERENCES user_features(user_id),
    movie_id                         BIGINT NOT NULL REFERENCES item_features(movie_id),
    rating                           DECIMAL(4,3) NOT NULL,
    event_timestamp                   BIGINT NOT NULL,
    event_datetime                    TIMESTAMP NOT NULL,
    recency_days                      DECIMAL(10,3),
    user_interaction_seq_num           INTEGER,
    days_since_user_prev_rating         DECIMAL(10,3),
    user_avg_rating                    DECIMAL(4,3),
    user_activity_percentile           DECIMAL(5,4),
    item_avg_rating                    DECIMAL(4,3),
    item_popularity_percentile          DECIMAL(5,4),
    rating_dev_from_user_avg            DECIMAL(5,4),
    rating_dev_from_item_avg            DECIMAL(5,4),
    user_item_cross_rating              DECIMAL(6,4),
    user_activity_x_item_popularity      DECIMAL(5,4),
    item_trending_score                 DECIMAL(5,4),
    user_genre_affinity_for_item          DECIMAL(5,4),
    top_similar_user_id                 BIGINT,
    top_similar_user_similarity          DECIMAL(5,4),
    top_similar_item_id                 BIGINT,
    top_similar_item_similarity          DECIMAL(5,4),
    cf_predicted_rating                  DECIMAL(4,3),
    feature_version                    VARCHAR(16) NOT NULL,
    computed_at                        TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_interaction_user ON interaction_features (user_id);
CREATE INDEX IF NOT EXISTS idx_interaction_movie ON interaction_features (movie_id);
CREATE INDEX IF NOT EXISTS idx_interaction_version ON interaction_features (feature_version);

-- ------------------------------------------------------------
-- FEATURE METADATA
-- Catalog of every engineered feature: which table/entity it
-- lives on, its type, a human description and the version it
-- was introduced in. Populated by setup_feature_store().
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feature_metadata (
    feature_name     VARCHAR(128) NOT NULL,
    version          VARCHAR(16) NOT NULL,
    entity_type      VARCHAR(32) NOT NULL,
    source_table     VARCHAR(64) NOT NULL,
    dtype            VARCHAR(32),
    description      VARCHAR(512),
    created_at       TIMESTAMP NOT NULL,
    PRIMARY KEY (feature_name, version)
);
CREATE INDEX IF NOT EXISTS idx_feature_metadata_entity ON feature_metadata (entity_type);
"""
    return schema


def design_sql_schema(output_path: str) -> str:
    """Generate and write schema.sql to `output_path`.

    Returns the path to the written file.
    """
    out_dir = Path(output_path)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "schema.sql"

    schema_sql = build_schema_sql()
    out_file.write_text(schema_sql, encoding="utf-8")
    logger.info("SQL schema written to %s", out_file)
    return str(out_file)
